// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Manager struct {
	Status          *int    `json:"status"`
	Details         *string `json:"details"`
	ScoreboardStats *int    `json:"scoreboardStats"`
}

type Managerial struct {
	Status          *int    `json:"status"`
	Details         *string `json:"details"`
	ScoreboardStats *int    `json:"scoreboardStats"`
}

type AddChallengeData struct {
	Name        string    `json:"name"`
	Description string    `json:"description"`
	Category    []*string `json:"category"`
	Tags        []*string `json:"tags"`
	Value       int       `json:"value"`
	Flags       string    `json:"flags"`
}

type AdminPreset struct {
	Name     string `json:"name"`
	Password string `json:"password"`
}

type Delfile struct {
	ID   string `json:"ID"`
	Name string `json:"name"`
}

type EditChallengeData struct {
	ID          string    `json:"ID"`
	Name        string    `json:"name"`
	Description string    `json:"description"`
	Category    []*string `json:"category"`
	Tags        []*string `json:"tags"`
	Value       int       `json:"value"`
	Flags       string    `json:"flags"`
}

type LoginInput struct {
	Username string `json:"username"`
	Password string `json:"password"`
}

type Notificationinp struct {
	Name        string `json:"name"`
	Description string `json:"description"`
}

type Notifiedit struct {
	ID          string `json:"id"`
	Name        string `json:"name"`
	Description string `json:"description"`
}

type Public struct {
	ID         string `json:"ID"`
	Visibility bool   `json:"visibility"`
}

type RegisterAdminData struct {
	Email    string `json:"email"`
	Username string `json:"username"`
	Password string `json:"password"`
	Secret   string `json:"secret"`
}

type RegisterInput struct {
	Email    string `json:"email"`
	Username string `json:"username"`
	Password string `json:"password"`
	Age      int    `json:"age"`
	Gender   string `json:"gender"`
}

type Resetpwd struct {
	Oldpwd  string `json:"oldpwd"`
	Newpwda string `json:"newpwda"`
	Newpwdb string `json:"newpwdb"`
}

type Scoreb struct {
	User *User `json:"user"`
}

type Useredit struct {
	Username    *string `json:"username"`
	Fullname    *string `json:"fullname"`
	Age         *string `json:"age"`
	Gender      *string `json:"gender"`
	Institution *string `json:"institution"`
	Contact     *string `json:"contact"`
	Place       *string `json:"place"`
	District    *string `json:"district"`
	State       *string `json:"state"`
}
